### ISSUE TITLE
Utils?

### ISSUE THREAD

**Issue by DSohl** [JPC-AV/JPC_AV_videoQC#26]
Hey, it's the end of the day and there's probably an obvious fix to this that I'm not seeing, but I tried running (for the first time) the process_av found in AV_Spex, and got this:

```
≈:≈ python /Users/medialab/github/jpc/videoQC/AV_Spex/process_av.py --profile step1 /Users/medialab/Desktop/JPC/20240313/JPC_AV_01672 
Traceback (most recent call last):
  File "/Users/medialab/github/jpc/videoQC/AV_Spex/process_av.py", line 21, in <module>
    from utils.log_setup import logger
ModuleNotFoundError: No module named 'utils'
```

Where do I find Utils?

**Comment by eddycolloton** [comment]
whoops! This is my fault. For the import statements to work w/ 'utils.[file_name]' there need to be __init__.py files in all the directories that store .py files. I have them locally but forgot to push them to github! I have pushed them just now, so if you re fetch and pull then it should fix this error.

**Comment by eddycolloton** [comment]
Whoops again! Some of the other files weren't added to utils or checks either. Should be in there now? fingers crossed. https://github.com/JPC-AV/JPC_AV_videoQC/commit/b982fb8fe5f91f0cb5e856f0e5fc2577bde14d86

**Comment by DSohl** [comment]
Still getting an error saying "No module named 'encoder_settings_check,' but I see that at /Users/medialab/github/jpc/videoQC/AV_Spex/checks/encoder_settings_check.py 

```
≈:≈ python /Users/medialab/github/jpc/videoQC/AV_Spex/process_av.py --profile step1 /Users/medialab/Desktop/JPC/20240313/JPC_AV_01672 

config.yaml sourced from /Users/medialab/github/jpc/videoQC/config/config.yaml
command_config.yaml sourced from /Users/medialab/github/jpc/videoQC/config/command_config.yaml
Traceback (most recent call last):
  File "/Users/medialab/github/jpc/videoQC/AV_Spex/process_av.py", line 29, in <module>
    from checks.ffprobe_check import parse_ffprobe
  File "/Users/medialab/github/jpc/videoQC/AV_Spex/checks/ffprobe_check.py", line 11, in <module>
    from encoder_settings_check import parse_encoder_settings
ModuleNotFoundError: No module named 'encoder_settings_check'
```

**Comment by eddycolloton** [comment]
Ah, looks like that import statement is missing the module prefix statement. Interesting that it worked on my computer without it, but not on yours. 

Instead of "from encoder_settings_check import parse_encoder_settings" it should say: 
"from checks.encoder_settings_check import parse_encoder_settings"

Most of the scripts import the logger and nothing else, sometimes the config, so this 'checks' import slipped through the cracks.

Anyway, I've pushed a quick fix, let me know if that works.
